### PR TITLE
Add the login user into "docker-snap" group in dockerd-wrapper.

### PR DESCRIPTION
**Pull request by adglkh**
This change add the login user into system so that there is no need
for end-user to switch to "docker-snap" user or root and people can
run docker command with the login user without sudo.

### CODE REVIEW

**Comment by arapulido** [comment]
Looks good, let's merge it

**Comment by chuckbutler** [comment]
Has this been published yet? I'm getting users asking me if the docker-snap requires sudo to function. Looks like it may be pending a release?

**Comment by adglkh** [comment]
Yes, I've published this on stable channel.
http://paste.ubuntu.com/24457493/

Regarding the question, docker-snap requires sudo to function?
No, it doesn't. Actually, we elaborate how to use docker without sudo in
docker.help.
The manual setup also helps us bypass the confinement issue we have on UC16.
That's why the manual setup is required before using docker-snap.
@Charles, please let me know if you have any further question.
Thanks.

BR
Gary.Wzl


2017-04-26 3:25 GMT+08:00 Charles Butler <notifications@github.com>:

**Comment by chuckbutler** [comment]
I went and did some digging. Sorry for the confusion. I had opened this bug before doing self discovery and found I wasn't well informed :)

:+1:   Thanks for the follow up

**Pull request merged**
