### PR TITLE
Update to engine 1.13, compose 1.10

### PR DESCRIPTION
**Pull request by mikedougherty**
Note: these versions aren't released yet, but are expected to be very shortly (going through final RC testing).

notes:
* some patches needed removing, others needed updating.
* we now need golang 1.7 to build, but there doesn't appear to be an official deb for it so i used an existing PPA
* docker now produces separate client and daemon binaries

cc @lool @andrewhsu

### CODE REVIEW

**Comment by mikedougherty** [comment]
Both are released + tagged now, merging this!

**Comment by mikedougherty** [comment]
Both are released/tagged now, @lool would you mind merging this? then we can see about getting some 1.13 builds into the store :)

**Comment by lool** [comment]
Sorry for the delay, am currently travelling – back Friday

**Comment by lool** [comment]
Would you be able to push this to the edge channel?

**Pull request merged**
